version: '3.6'

services:
  eureka:
    image: eureka
    build: .
    ports:
      - 8761:8761
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    networks: 
      - pos-unipe
  zuul:
    image: zuul
    build: 
      context: .
      dockerfile:  zuul.Dockerfile
    ports:
      - 8080:8080
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    deploy:
      update_config:
        delay: 10s
    networks: 
      - pos-unipe
    depends_on: 
      - eureka
  japao:
    image: japao
    build: 
      context: .
      dockerfile:  japao.Dockerfile
    ports:
      - 8089:8089
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    deploy:
      update_config:
        delay: 10s
    networks: 
      - pos-unipe
    depends_on: 
      - eureka
  argentina:
    image: argentina
    build: 
      context: .
      dockerfile:  argentina.Dockerfile
    ports:
      - 8040:8040
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    deploy:
      update_config:
        delay: 10s
    networks: 
      - pos-unipe
    depends_on: 
      - eureka
  belgica:
    image: belgica
    build: 
      context: .
      dockerfile:  belgica.Dockerfile
    ports:
      - 8050:8050
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    deploy:
      update_config:
        delay: 10s
    networks: 
      - pos-unipe
    depends_on: 
      - eureka
  brasil:
    image: brasil
    build: 
      context: .
      dockerfile:  brasil.Dockerfile
    ports:
      - 8060:8060
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    deploy:
      update_config:
        delay: 10s
    networks: 
      - pos-unipe
    depends_on: 
      - eureka
  holanda:
    image: holanda
    build: 
      context: .
      dockerfile:  holanda.Dockerfile
    ports:
      - 8090:8090
    environment: 
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    restart: always
    deploy:
      update_config:
        delay: 10s
    networks: 
      - pos-unipe
    depends_on: 
      - eureka
networks: 
  pos-unipe:
    name: pos-unipe
    driver: bridge
